export default {
  UNKNOWN: 'APP-000',
  APPLICATION_PROPERTY_MISSING: 'APP-001',
  ILLEGAL_ARGUMENT: 'APP-002',
  UNMAPPED_INVALID_ATTRIBUTE: 'APP-003',
  DATA_ACCESS_ERROR: 'APP-004',
  PARAMETER_MISSING: 'APP-005'
} as const
